"""Added likes column to blog_posts

Revision ID: 948a432f39a6
Revises: 5d06a6cbf576
Create Date: 2025-03-16 05:45:08.919986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948a432f39a6'
down_revision = '5d06a6cbf576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_by', sa.PickleType(), nullable=True))
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('blog_posts_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('comments_post_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comments_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'blog_posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verified')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_author_id_fkey', 'users', ['author_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('comments_post_id_fkey', 'blog_posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('blog_posts_author_id_fkey', 'users', ['author_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('liked_by')

    # ### end Alembic commands ###
